# Generated by Django 6.1.dev20251019181316 on 2025-10-23 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(max_length=200, verbose_name='本文')),
                ('page_date', models.DateField(verbose_name='日付')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
