# Generated by Django 6.1.dev20251019181316 on 2025-10-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabemory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tabemory/picture/', verbose_name='写真'),
        ),
    ]
